### PR TITLE
fix: skip extraction of threadMetadata for Gmail Ads

### LINKED ISSUE #943: Bug:
**Describe the bug**
When switching to a different category tab in Gmail, errors are reported in the console:
```
pageWorld.js:2 Error in injected script Error: Errors in thread row parsing
    at P (pageWorld.js:2:1)
    at pageWorld.js:2:1
    at HTMLDocument.<anonymous> (pageWorld.js:2:1) {errors: [
        "failed to find timeSpan",
        "failed to find peopleDiv"
    ]}
```

**To Reproduce**

1. [Enable category tabs](https://support.google.com/mail/answer/3094499) in Gmail
2. Open the developer console
3. Open inbox and click to a different tab (e.g. _Promotions_)

**Screenshots**
inboxsdk-screenshot
inboxsdk-console

### PR DESCRIPTION
**Pull request by wegry**
Skip trying to extract metadata for ads in Gmail's Promotions tab.

Screenshot 2023-08-03 at 16 21 54

The way I've checked parsing after the change was with the sample extension found here: https://github.com/InboxSDK/InboxSDK/blob/833d6b8bcca9646c36b627f67e2f73958364e3f7/examples/thread-rows/content.js.

Closes #943

### CODE REVIEW

File: src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts [hunk 1]
```diff
@@ -278,15 +278,18 @@ class GmailThreadRowView {
...
+   * It should almost always synchronously ready immediately, but there's
+   * a few cases such as with multiple inbox or the drafts page that it needs a moment.
+   * make sure you take until by on the @see GmailThreadRowView#getStopper because waitForReady
+   * must not be called after the GmailThreadRowView is destroyed
+   */
   waitForReady(): Kefir.Observable<GmailThreadRowView, unknown> {
     const time = [0, 10, 100, 1000, 15000];
 
-    const step: any = () => {
+    const step = (): Kefir.Observable<GmailThreadRowView | never, unknown> => {
```
Comment (wegry) [inline src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts:292]:
```suggestion
    const step = (): Kefir.Observable<GmailThreadRowView, unknown> => {
```

**Review by Macil — APPROVED** [review]
