### PR TITLE
proposed fix for: SelectorError: Failed to find element with selector: table.Bs > tr, .ao8:has(.a98.iY)

### LINKED ISSUE #1078: `Compose.registerComposeViewHandler` Registered Compose View Handler does not fire on Reply/Reply All/Forward
This is probably related to the Gmail changes that occurred yesterday, as this behavior started yesterday as well, in a small number of Gmail accounts. We are running the latest InboxSDK 2.1.15

Our extension "pops-out" Compose, Reply, Reply-All, and Forwards. On a small number of Gmail accounts, the Reply/Reply All/Forward threads no longer auto-pop-out. Compose does still auto-pop-out.

I can see that the Registered Compose View Handler does not fire on Reply/Reply All/Forward, so I'm guessing the selector is incorrect.

Below are two images of Chrome Dev Tools searching for .a98.iY . The selector is found in both working and non-working, but the surrounding DOM elements are quite different between the two:

**Works properly:**
EmileWorks a98 iY

**Does not work:**
TimDoesNotWork a98 iY

Hacking on this a bit, it seems the selector in the Not Working scenario should be '.nH.UG.id:has(.a98.iY)' instead of '.nH.g.id:has(.a98.iY)' , but I still can't get the Compose View Handler to fire.

### PR DESCRIPTION
**Pull request by Alex-Chopard**
Hi, sadly we experiencing more issues with the preview pane and the detection of a selected conversation / switch to another conversation.
As I'm able to reproduce the issue on the test account, I trying a fix.

Fill free to ask if you have any question / suggestion about this PR.

Error in the console:
Screenshot 2023-11-22 at 11 58 46

DOM with preview panel enabled and no conversation selected:
`.ao8` is well found but not `.a98.iY`
Screenshot 2023-11-22 at 12 00 33

DOM with preview panel enabled and a conversation selected:
`.apa` has been replaced with `.a98.iY`
Screenshot 2023-11-22 at 12 01 28

Without the fix:

https://github.com/InboxSDK/InboxSDK/assets/29271954/33666754-2b65-40d0-b863-8b736a854ad0

With the fix:

https://github.com/InboxSDK/InboxSDK/assets/29271954/3c2363a8-d635-4cf6-9e62-83f51d3bb3eb

#1071

Closes #1078

### CODE REVIEW

File: src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts [hunk 1]
```diff
@@ -432,7 +432,9 @@ class GmailRouteView {
       (event) =>
         !!event.el.querySelector('.if') ||
         !!event.el.querySelector('.PeIF1d') ||
-        !!event.el.querySelector('.a98.iY'),
+        !!event.el.querySelector('.a98.iY') ||
+        (event.el.classList.contains('a98') &&
+          event.el.classList.contains('iY')),
```
Comment (wegry) [inline src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts:437]: nit: Could this be simplified to

```typescript
        event.el.matches('.a98.iY'),
```

**Comment by wegry** [comment]
Thanks for this @Alex-Chopard. I'll try testing against my accounts to see if the existing behavior holds there. @bkorobeinikov might want to take a look as well. We'll try getting back to you by 18:00 UTC about pulling this in.

File: src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts (hunk 1 above)
Comment (wegry) [inline src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts:437]: nit: Could this be simplified to

```suggestion
        !!event.el.querySelector('.a98.iY') ||
        event.el.matches('.a98.iY'),
```

Comment (Alex-Chopard) [reply src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts:437]: Indeed, I did not know this method, thanks 🙏

**Review by wegry — APPROVED** [review]
I'm inclined to say we should move forward with this PR. It may fix both #1071 and #1078. I would like another one of the folks I've flagged as a reviewer bless it though.

**Comment by wegry** [comment]
This is included in `@inboxsdk/core@2.1.19`.
